setwd("C:/TB_datamining")
getwd()
install.packages("C50")
install.packages("printr")
library(C50)
library(printr)
dataset <- read.csv("superstore_dataset.csv", sep = ",")
View(dataset)
dataset$Segment <- as.factor(dataset$Segment)
model <- C5.0(Segment ~., data=dataset)
summary(model)
plot(model)
datatesting <- dataset[,1:5]
predictions <- predict(model, dataset)
table(predictions, dataset$Segment)